"""Reusable email body builders for payroll notifications.

Goal: Improve deliverability by providing well-structured, benign wording,
plain text + HTML, and consistent footer with contact and unsubscribe hint.
"""
from datetime import datetime
from typing import Dict, List

FOOTER_TEXT = (
    "\n--\nPayroll Automation System\n"
    "This message was sent automatically by the internal payroll application. "
    "If you believe you received it by mistake, please contact payroll@company.example."
)

FOOTER_HTML = (
    "<hr style='border:none;border-top:1px solid #ccc;margin:24px 0;'>"
    "<p style='font-size:12px;color:#666;line-height:1.4'>"
    "Payroll Automation System<br>"
    "This message was sent automatically by the internal payroll application. "
    "If you believe you received it by mistake, please contact "
    "<a href='mailto:payroll@company.example'>payroll@company.example</a>."
    "</p>"
)

def build_payslip_subject(period: datetime) -> str:
    return f"Your {period.strftime('%B %Y')} payslip is available"

def build_payslip_bodies(employee_first: str) -> Dict[str, str]:
    text = (
        f"Hello {employee_first},\n\n"
        "Your payslip for this month is attached as a PDF generated by the Payroll Automation System.\n"
        "It summarizes your salary, working days, and applicable bonuses or deductions.\n\n"
        "If you have any questions about the information shown, please reach out to the Payroll team."
        + FOOTER_TEXT
    )
    html = (
        f"<p>Hello {employee_first},</p>"
        "<p>Your payslip for this month is attached as a PDF generated by the Payroll Automation System.</p>"
        "<p>It summarizes your salary, working days, and applicable bonuses or deductions.</p>"
        "<p>If you have any questions about the information shown, please contact "
        "<a href='mailto:payroll@company.example'>the Payroll team</a>.</p>"
        f"{FOOTER_HTML}"
    )
    return {"text": text, "html": html}

def build_aggregate_subject(period: datetime) -> str:
    return f"Monthly Compensation Summary - {period.strftime('%B %Y')}"

def build_aggregate_bodies(employee_first: str, bonuses: List[Dict]) -> Dict[str, str]:
    bonus_line = (
        f"This summary includes {len(bonuses)} bonus item(s)." if bonuses else
        "This summary does not include any bonus entries for this period."
    )
    text = (
        f"Hello {employee_first},\n\n"
        "Attached is your monthly compensation summary (CSV) generated by the Payroll Automation System.\n"
        f"{bonus_line}\n"
        "It lists your working days, leave days, and the details used in the salary calculation.\n\n"
        "For any clarification, please contact the Payroll team."
        + FOOTER_TEXT
    )
    html = (
        f"<p>Hello {employee_first},</p>"
        f"<p>Your monthly compensation summary (CSV) is attached. {bonus_line}</p>"
        "<p>It lists your working days, leave days, and the details used in the salary calculation.</p>"
        "<p>If you have questions, please reach out to "
        "<a href='mailto:payroll@company.example'>the Payroll team</a>.</p>"
        f"{FOOTER_HTML}"
    )
    return {"text": text, "html": html}


def build_neutral_document_bodies(employee_first: str) -> Dict[str, str]:
    """Build a neutral, non-payroll-specific document notification.

    This wording avoids payroll-specific keywords and is suitable for
    environments where neutral messaging is required.
    """
    text = (
        f"Hello {employee_first},\n\n"
        "Your requested document is attached. Please review and retain for your records.\n\n"
        "--\nAutomated Notification"
    )
    html = (
        f"<p>Hi {employee_first},</p>"
        "<p>Your requested document is attached. Please review and retain for your records.</p>"
        "<p style='font-size:12px;color:#666'>Automated Notification</p>"
    )
    return {"text": text, "html": html}

__all__ = [
    "build_payslip_subject",
    "build_payslip_bodies",
    "build_aggregate_subject",
    "build_aggregate_bodies",
    "build_neutral_document_bodies",
]
