services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: slip_db
      POSTGRES_USER: slip_user
      POSTGRES_PASSWORD: slip_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=slip_db
      - DJANGO_DB_USER=slip_user
      - DJANGO_DB_PASSWORD=slip_pass

volumes:
  postgres_data:
