# Generated by Django 5.2.7 on 2025-10-29 13:44

import app.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department_alter_employee_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='month',
            field=models.IntegerField(default=app.db.models.current_month),
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(default=app.db.models.current_year),
        ),
    ]
