# Generated by Django 5.2.7 on 2025-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_attendance_month_attendance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='expected_working_days',
            field=models.IntegerField(blank=True, default=22, help_text='Override default business days for proration (default 22)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'year', 'month')},
        ),
    ]
