# Generated by Django 5.2.7 on 2025-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee_base_salary_employee_expected_working_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cnp',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
