# Generated by Django 5.2.7 on 2025-11-04 08:18

import app.db.models.attendance
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_idempotencyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('revoked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='month',
            field=models.IntegerField(default=app.db.models.attendance.current_month),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(default=app.db.models.attendance.current_year),
        ),
    ]
